apiVersion: argoproj.io/v1alpha1
kind: Application
# This is an ArgoCD-specific resource type (not standard Kubernetes).
# It tells ArgoCD: watch this Git repo folder and keep the cluster in sync with it.
#This is not a standard Kubernetes resource — it is an ArgoCD-specific resource that tells ArgoCD its job.
#
#  - source — watch this GitHub repo, this branch, this folder
#  - destination — deploy into this cluster and namespace
#  - prune: true — if you delete a file from k8s/, delete the corresponding resource from the cluster
#  - selfHeal: true — if someone manually edits the cluster with kubectl edit, revert it back to match Git.
# Git is always the single source of truth.
metadata:
  name: hello-api
  namespace: argocd
  # Must be in the argocd namespace — this is where ArgoCD looks for Application resources.
spec:
  project: default

  source:
    repoURL: https://github.com/ankittcsbackup/OpenAPIProject.git
    # The GitHub repo ArgoCD will watch.
    targetRevision: gitops
    # ArgoCD watches the gitops branch, not main.
    # main = application code changes by developers.
    # gitops = manifest/infrastructure changes pushed by the CD bot.
    path: k8s
    # The folder inside the repo that contains your Kubernetes manifests.
    # ArgoCD only watches this folder — changes elsewhere do not trigger a deploy.

  destination:
    server: https://kubernetes.default.svc
    # This is the internal address of your local Kubernetes cluster.
    # Because ArgoCD runs inside the same cluster, it uses this internal address.
    namespace: hello-api
    # The namespace where your app will be deployed.

  syncPolicy:
    automated:
      prune: true
      # prune: true — if you delete a manifest from k8s/ folder, ArgoCD deletes
      # the corresponding resource from the cluster automatically.
      selfHeal: true
      # selfHeal: true — if someone manually changes something in the cluster
      # (e.g. kubectl edit), ArgoCD automatically reverts it back to match Git.
      # Git is always the source of truth.
    syncOptions:
      - CreateNamespace=true
      # CreateNamespace=true — ArgoCD will create the hello-api namespace
      # automatically if it does not exist. No need to run kubectl create namespace.
